### ISSUE TITLE
Using in groups

### ISSUE THREAD

**Issue by Sigmanor** [EdJoPaTo/telegraf-stateless-question#9]
Hello. 

Sorry for maybe dumb question, but I can't find answers in the **readme**. This package can be used in the groups? Or only in the private chat with bot? Because example from the **readme** working (for me) incorrect in groups, it's force reply to all users in the group, not only for user that triggers reply. Maybe I missing something?

**Comment by EdJoPaTo** [comment]
Personally I havnt used this in a group yet and I see your point. When thinking about this I remembered there was an option to make this reply only for one person. Checking the API it has a `selective` option for [ForceReply](https://core.telegram.org/bots/api#forcereply).

Reading on how selective works it requires to mention the user or itself being replied to a message of the user. For example when used from my inline menu there is no message triggering this so the second option is not working there.

This library provides a way to send the message youself (check the last two lines of the usage example in the readme). This could be modified to add `selective: true` and either mention a user or with `reply_to_message_id`.

If that works well… Maybe this library should use the selective force reply over the default one? As selective requires one of the two conditions it should default back to require the reply from everyone anyway. Any thoughts on this?

Thanks for bringing this up!

**Comment by Sigmanor** [comment]
> Checking the API it has a `selective` option for [ForceReply](https://core.telegram.org/bots/api#forcereply).

Yes, seems this what I need, but I can't figure how to use it.

```javascript
const unicornQuestion = new TelegrafStatelessQuestion('unicorns', ctx => {
	console.log('User thinks unicorns are doing:', ctx.message.text)
})

bot.use(unicornQuestion.middleware())

bot.command('unicorn', async ctx => {
     ctx.replyWithMarkdown('What are unicorns doing?' + unicornQuestion.messageSuffixMarkdown(), {parse_mode: 'Markdown', reply_markup: {force_reply: true, selective: true, reply_to_message_id: ctx.message.message_id}})
})
```

This code do not force reply, I need manually reply, or maybe I'm doing something wrong?

**Comment by EdJoPaTo** [comment]
For mentioning users: You can use the inline mention (like the one for markdown: `[inline mention of a user](tg://user?id=123456789)`) as they are documented in the [Formatting Options](https://core.telegram.org/bots/api#formatting-options). That works with every user but using the `reply_to_message_id` as you got working seems better to me.

Using selective by default should be ignored when not done with a reply (which the default never does) and when not done with mentions. Different behavior just because of mentioning someone seems strange to me so documenting this example in the readme seems like the best approach to be.
